import type { Metadata } from 'next'
import { ThemeProvider } from '@/hooks/useThemeProvider'
import { Inter as FontSans } from 'next/font/google'
import Navbar from '@/components/Navbar'
import './globals.css'

import { cn } from '@/lib/utils'

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Youngla',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased ease-in duration-200',
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <main className='relative flex flex-col min-h-screen'>
            <Navbar />
            <div className='flex-grow flex-1'>{children}</div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
